<?hh
namespace Ninjack\Core\Enum;

/**
 * SQL data type (only mariadb for the moement)
 * (https://mariadb.com/kb/en/library/data-types/)
 */
enum DataBaseColumnType: string {

  //numeric
  SQL_TINYINT = "TINYINT";
  SQL_BOOLEAN = "BOOLEAN";
  SQL_SMALLINT = "SMALLINT";
  SQL_MEDIUMINT = "MEDIUMINT";
  SQL_INT = "INT";
  SQL_INTEGER = "INTEGER";
  SQL_BIGINT = "BIGINT";
  SQL_DECIMAL = "DECIMAL";
  SQL_DEC = "DEC";
  SQL_NUMERIC = "NUMERIC";
  SQL_FLOAT = "FLOAT";
  SQL_DOUBLE = "DOUBLE";
  SQL_DOUBLE_PRECISION = "DOUBLE PRECISION";

  //string
  SQL_CHAR = "CHAR";
  SQL_VARCHAR = "VARCHAR";
  SQL_BINARY = "BINARY";
  SQL_CHAR_BYTE = "CHAR BYTE";
  SQL_VARBINARY = "VARBINARY";
  SQL_TINYBLOB = "TINYBLOB";
  SQL_BLOB = "BLOB";
  SQL_TEXT = "TEXT";
  SQL_MEDIUMBLOB = "MEDIUMBLOB";
  SQL_LONGBLOB = "LONGBLOB";
  SQL_TINYTEXT = "TINYTEXT";
  SQL_MEDIUMTEXT = "MEDIUMTEXT";
  SQL_LONGTEXT = "LONGTEXT";
  SQL_JSON = "JSON";
  SQL_ENUM = "ENUM";

  //Date and Time
  SQL_DATE = "DATE";
  SQL_TIME = "TIME";
  SQL_DATETIME = "DATETIME";
  SQL_TIMESTAMP = "TIMESTAMP";
  SQL_YEAR = "YEAR";

}
